### ISSUE TITLE
[ipfs/tar-utils] Deprecate Repository

### ISSUE THREAD

**Issue by hacdias** [ipfs/go-libipfs#10]
This repository was moved to https://github.com/ipfs/libkubo/

Should we deprecate it then? I think we should deprecate and make a link to `libkubo` to avoid causing confusion to other developers and making it unclear on which code is being maintained.

/cc @BigLep @guseggert

**Comment by guseggert** [comment]
It's waiting on a review of https://github.com/ipfs/kubo/pull/9415

**Comment by guseggert** [comment]
I went ahead and finished this up and archived ipfs/tar-utils
