### ISSUE TITLE
gateway: create example that proxies to requests to ?format=raw

### ISSUE THREAD

**Issue by lidel** [ipfs/go-libipfs#142]
Make a binary that runs the libipfs gateway code using a virtual blockstore that sends [application/vnd.ipld.raw](https://www.iana.org/assignments/media-types/application/vnd.ipld.raw) (`?format=raw`) requests to some gateway.

This will be a good warmup before we get custom blockstore from Saturn,
will also allow us to quickly see if the performance is as bad as we expect.

- for now in the same repo, `examples/gateway/block-proxy-gateway` (its late, needs better name)
- CLI tool with two  parameters: port to listen and URL of gateway that supports `?format=raw` responses

This may depend on, or help with  cleaning up API in #61

**Comment by Jorropo** [comment]
Related: https://github.com/ipfs/go-libipfs/issues/139 (tangently)
