### ISSUE TITLE
gateway: ipfs_http_gw_get_duration_seconds metric is not updated

### ISSUE THREAD

**Issue by lidel** [ipfs/go-libipfs#162]
https://github.com/ipfs/go-libipfs/blob/1c6ed2e96f7753a3452607e2a429311a31099cf4/gateway/handler.go#L240-L242

It should be updated  for every request type (global histogram across all response types), does not seem to be happening atm

**Comment by hacdias** [comment]
~@lidel it seems to be updating on my side (tried multiple formats, both under ipfs and ipns). The count increases 1 with every successful request. Do you have any example of requests that do not update this metric?~

Funnily enough, it updates with every successful request except for actual UnixFS files 🥲 I'll fix this.
