### ISSUE TITLE
gateway: add metric for implicit `index.html` 

### ISSUE THREAD

**Issue by lidel** [ipfs/go-libipfs#166]
Ref. https://github.com/ipfs/go-libipfs/blob/1c6ed2e96f7753a3452607e2a429311a31099cf4/gateway/handler.go#L244-L253

We track (histograms):
-  `gw_unixfs_file_get_duration_seconds`  (files) and
-   `gw_unixfs_gen_dir_listing_get_duration_seconds` (generated html dir listings). 

We are missing a metric that tracks the case where request was for a directory with index.html. It is necessary to see how popular this use case is, and if we should introduce optimizations to avoid round trips for `index.html`. 

## Proposed change

Add new histogram ([here?](https://github.com/ipfs/go-libipfs/blob/1c6ed2e96f7753a3452607e2a429311a31099cf4/gateway/handler_unixfs_dir.go#L78-L80) for tracking how long it took to find and load `index.html` when a dir path was requested:

-   `gw_unixfs_dir_index-html_get_duration_seconds`

**Comment by hacdias** [comment]
Comment moved to #168.
