### ISSUE TITLE
Move out RAPIDE experiment

### ISSUE THREAD

**Issue by BigLep** [ipfs/go-libipfs#180]
## Done Criteria
RAPIDE experimental work (PRs and issues) are out of go-libipfs until either:
1. We are better setup to handle experimental work OR
2. Project meets the [inclusion requirements](https://github.com/ipfs/go-libipfs#should-i-add-my-ipfs-component-to-go-libipfs)

## Why Important
It's not a good look to spam the go-libipfs repo with highly experimental code and issues. It would be one thing if we had clear documentation on how we handle experimental functionality and a tight triage process and views sorting out the experimental / aspirational work from the nuts and bolts of bugs to existing functionality. We'll get there, but we're not there currently. 

## Notes
This will get moved within the IPFS org (e.g., http://github.com/ipfs/go-libipfs-rapide ) since that makes it easier to move issues.

**Comment by Jorropo** [comment]
Done it now lives at https://github.com/ipfs/go-libipfs-rapide
