### ISSUE TITLE
Document how existing migrated repo consumers update to go-libipfs

### ISSUE THREAD

**Issue by BigLep** [ipfs/go-libipfs#189]
## 👋  If wondering how update to use boxo from another ipfs/* repo that is no longer maintained, read here...

PLACEHOLDER TODO - this text will get filled in with more details once this issue is completed, likely just pointing to to-be-created docs.  This is relevant since "[not maintained messaging](https://github.com/ipfs/boxo/issues/202#issuecomment-1485963196)" points here.

----
## Done Criteria
There are docs that state the steps someone would take for upgrading to go-libipfs for any existing dependencies they had of repos that have been moved into go-libipfs.

## Why Important
1. Ease the burden for those impacted by the transition.
2. Ensure maintainers are thinking about the experience of those impacted by this transition. 

## Notes
1. It should be clear what repos have moved over.
2. If there is tooling (e.g., https://github.com/ipfs/go-libipfs/issues/181), that should be linked to.

**Comment by BigLep** [comment]
@guseggert : do you have thoughts on where these docs will live?  Will we have a md file under `docs`?  `docs/how_to_switch_to_boxo.md` ?

**Comment by guseggert** [comment]
I've added documentation on how to migrate in this PR: https://github.com/ipfs/boxo/pull/243
