### ISSUE TITLE
Provide Stock Libp2p Config For IPFS

### ISSUE THREAD

**Issue by hannahhoward** [ipfs/go-libipfs#208]
Yesterday I learned that if I initialize a Libp2p node with default options, I won't be able to connect to some large IPFS providers (like web3.storage). 

Most prominently, this is cause JS based IPFS implementations are usually still using Mplex as opposed to Yamux. That said, digging through Kubo source code, there are SO many customizations to Libp2p parameters it's hard to know how much might be different, and how much this will affect connectivity.

To make things easier for folks to people to spin up an IPFS stack using this library, it would be nice, either as a module or in example code, to provide an ideal stock configuration for maximizing connectivity on the network.

Currently, figuring out the right Libp2p configs requires scanning a ton of Kubo startup code, which, I can do, having poured through it several times over the years, but is a HUGE lift for anyone new to the ecosytem.

For reference, where we ended up in Lassie after the exercise of copying Kubo configs is here: https://github.com/filecoin-project/lassie/pull/157

**Comment by Jorropo** [comment]
- https://github.com/ipfs/kubo/pull/9641
- https://github.com/ipfs/js-ipfs/issues/4318

I also remember discussions about upgrading web3.storage and I'm pretty sure web3.storage supports yamux now (there is a bug in the latest libp2p release where websocket connections have issues).

**Comment by hannahhoward** [comment]
@Jorropo they rolled it back due to a bug in JS-yamux -- https://github.com/elastic-ipfs/bitswap-peer/pull/195

**Comment by hannahhoward** [comment]
they plan to add it back I guess -- https://github.com/elastic-ipfs/elastic-ipfs/issues/25

**Comment by Jorropo** [comment]
> they rolled it back due to a bug in JS-yamux

Ah.

> they plan to add it back I guess

Well should get fixed at some point I guess.

We still want to remove MPLEX support from Kubo because this is incompatible with the backpressure control we want to add to the Bitswap Server.

**Comment by lidel** [comment]
Triage notes:
- the priority for handling mplex divergence is much lower than before
- if the only divergence in defaults between ipfs ecosystem and the default libp2p is mplex, this does not feel enough to justify  indirection introduced in https://github.com/ipfs/boxo/pull/230
  - ecosystem should remove dependency on mplex instead (already in progress)
- if there are better use cases than mplex, we can revisit/reopen this

Closing for now
