### ISSUE TITLE
Migrate go-ipfs-files

### ISSUE THREAD

**Issue by hacdias** [ipfs/go-libipfs#24]
- [x] Merge https://github.com/ipfs/go-libipfs/pull/20
- [x] Release this repository
- [x] Update imports:
	- Merge:
		- [x] https://github.com/ipfs/go-ipfs-cmds/pull/233
		- [x] https://github.com/ipfs/interface-go-ipfs-core/pull/97
		- [x] https://github.com/ipfs/go-unixfs/pull/134
		- [x] https://github.com/ipfs/go-graphsync/pull/399
	- After all above are merged, release:
		- [x] go-ipfs-cmds https://github.com/ipfs/go-ipfs-cmds/pull/235
		- [x] interface-go-ipfs-core https://github.com/ipfs/interface-go-ipfs-core/pull/100
		- [x] go-unixfs https://github.com/ipfs/go-unixfs/pull/136
		- [x] go-graphsync https://github.com/ipfs/go-graphsync/pull/400
		- [x] kubo: https://github.com/ipfs/kubo/pull/9535 
- [x] Run `issues` and `clean-pull-requests` commands (https://github.com/guseggert/repo-migration-tools) in https://github.com/ipfs/go-ipfs-files
- [x] Archive https://github.com/ipfs/go-ipfs-files

**Comment by hacdias** [comment]
@guseggert could you take a look at all the linked PRs to update the versions? I want to start migrating (https://github.com/ipfs/kubo/issues/8543) from top to bottom to avoid plumbing 🪠, but I'm blocked by the linked PRs which are mostly for the bottom repositories.

**Comment by lidel** [comment]
Merged https://github.com/ipfs/kubo/pull/9535, feel free to continue with remaining steps :+1:
