### ISSUE TITLE
Enforce changelog updates in CI

### ISSUE THREAD

**Issue by guseggert** [ipfs/go-libipfs#267]
It'd be nice for CI to enforce changelog updates for each PR, or require explicit opt-out, so that when we start a release train, the release engineer doesn't need to cat-herd everyone to write changelog updates.

I've opened an issue here requesting this feature: https://github.com/pl-strflt/changelog-driven-release/issues/5

**Comment by galargh** [comment]
We met w/ Gus to chat about this some more. Here are the things we plan to do for this:
1. Introduce PR Template that nudges people toward filling out the changelog.
2. Add a GHA which checks whether the changelog has been updated. The contributor will have ability to bypass that check. Ideas for bypassing the check: description, title, label, comment.
