### ISSUE TITLE
Gateway metric tracking partial failures

### ISSUE THREAD

**Issue by willscott** [ipfs/go-libipfs#288]
The gateway already has some tracking of whether each request finished [successfully](https://github.com/ipfs/boxo/blob/main/gateway/handler.go#L307)
It would be useful to get a metric tracking the amount of successful vs unsuccessful requests, labeled by the type of request (car vs block vs unixfs vs codec).

**Comment by BigLep** [comment]
@lidel : this one missed our planning.  Are you aware of it?  Is this something we could squeeze in support of Rhea?

I agree we should emit a metric for each request and that each metric emitted should have dimensionality on:
* HTTP response code (particularly was it successful or not)
* request type (car, block, etc.)

**Comment by lidel** [comment]
- we already have metrics for all these things, but response code is not enough for streaming responses (could fail mid-stream).
- we can add more resolution to count failures mid-CAR-stream, initial plan from  https://github.com/ipfs/bifrost-gateway/issues/104#issuecomment-1552072033 below, i'll try to prioritize it 

--- 

_(late on my end, but wanted to write this down, read with pinch of salt)_

afaik we have one place where client may get 200 and then  experience an interrupted stream: `?format=car` 
(problem discussed in length, multiiple ways of dealing with this, but [none of solutions got accepted so far](https://www.notion.so/pl-strflt/Streaming-CARs-bfa54196ed0740eea3c23dd70efbe07b))

we already count successful fetches in `carStreamGetMetric` (produces `ipfs_http_gw_car_stream_get_duration_seconds_count`).

 what we could do  is to  update Vec produced by  `newHistogramMetric` and add "status"  [here](https://github.com/ipfs/boxo/blob/4fb455dd307a85a3d6ac6579400b4f81b80b5b16/gateway/metrics.go#L253), and then update all metrics we have to explicitly update"success". 

then, we can count success and failure separately. in case of CAR, we would increase failure counter inside or [this block](https://github.com/ipfs/boxo/blob/4fb455dd307a85a3d6ac6579400b4f81b80b5b16/gateway/handler_car.go#L82-L89), and then compare with the number of successes in `ipfs_http_gw_car_stream_get_duration_seconds_count`

@hacdias do you know if any other places than CAR and [TAR](https://github.com/ipfs/boxo/blob/4fb455dd307a85a3d6ac6579400b4f81b80b5b16/gateway/handler_tar.go#L84)?

**Comment by BigLep** [comment]
Thanks @lidel - good point about breakout by HTTP status code not being sufficient given failure by midstream.  

I obviously don't know how the code works but I'm wondering if the way to handle this is that we only emit the metric when we finish handling from the server side (boxo gateway) to the best of our ability, which could be fully completed or failed because mid-stream failure.  We then have these dimensions:
* status: completed or failed
* HTTP response code: n/a if it was a failed request, HTTP status code if we didn't fail midstream
* request type: car, block, etc.

I'm just thinking about how to keep this simple where the "n" on the metric speaks to the number of requests we attempted to handle, and then completion rates can be calculated with status=completed/n.  

(I don't know if those are best terminology.  I would think we should report like other HTTP proxies like nginx do, since they have to handle the same concerns of proxied connections failing midstream.)

**Comment by lidel** [comment]
Below two should give us enough visibility to reason about 
- https://github.com/ipfs/boxo/pull/311 is useful on its own, but in the context of this issue, allows us to see how many requests end up as success vs failure per specific content type
  - if there was a failure during processing of a specific response type, the counter added in this PR will be higher than the already existing success counter for specific content type, and the delta is the number of failures
    - Example (specific to type): if there is an error during streaming CAR response (after HTTP 200 OK status is already sent to the client),  the `ipfs_http_gw_request_types{type=application/vnd.ipld.car}`  will be higher than `ipfs_http_gw_car_stream_get_duration_seconds_count` (which is updated only at the end of successful  response)
    - Example (across types):  for flat files, `gateway.ServeContent` returns `dataSent` only on successful response. this means we only update `ipfs_http_gw_get_duration_seconds_count` on successful  (complete) response, and if there was a problem while streaming a file, we not update this counter.   Calculating % of errors is possible by comparing it with `ipfs_http_gw_request_types` (without `type` filter)
  - this feels like a good compromise, pretty future-proof, should not break during refactors. (in the past we had bugs where wiring too many metrics gave us a false sense of coverage, and after refactors we've stopped tracking some  types of requests)/
    
- https://github.com/ipfs/boxo/pull/312  adds `ipfs_http_gw_car_stream_fail_duration_seconds` which will show us how long a CAR response was being streamed to the client before it failed mid-stream (after HTTP 200 was already sent). If there is a system-wide  pattern (e.g. in Saturn L1s), we will see a lot of failures around a similar histogram bucket.
