### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by BigLep** [ipfs/go-libipfs#325]
# Scope
Latest changes in main.  This is being done in support of https://github.com/ipfs/kubo/issues/9814

Required

- [x] https://github.com/ipfs/boxo/pull/273
	- [x] This was reverted. Waiting for fixed version from @Jorropo: https://github.com/ipfs/boxo/pull/331
- [x] https://github.com/ipfs/boxo/pull/290
- [x] https://github.com/ipfs/boxo/pull/313
- [x] https://github.com/ipfs/boxo/pull/326

Optional

# Steps
TODO: Populate with the items in https://github.com/ipfs/boxo/blob/main/RELEASE.md#release-process

**Comment by hacdias** [comment]
Notes:

- #273 was reverted in 4c5c98b94b219d9870c3181f73a99d2f15edae7d. Do we still want it to go on 0.9? See #331.
- Still waiting for https://github.com/ipfs/boxo/pull/290.

**Comment by BigLep** [comment]
@hacdias 
> Do we still want it to go on 0.9

Yeah, we need it for addressing https://github.com/ipfs/kubo/issues/9703 and the related issues, and that is a blocker for Kubo (not going another release where don't have the operational fixes we committed to earlier in the year).

**Comment by hacdias** [comment]
Boxo 0.9.0 is released: https://github.com/ipfs/boxo/releases/tag/v0.9.0. Thanks @Jorropo for releasing.

**Comment by BigLep** [comment]
@hacdias : I documented one lesson learned from this release that I heard about.  Do you have any others to add to the release process? https://github.com/ipfs/boxo/pull/343

**Comment by hacdias** [comment]
@BigLep I mostly reviewed the PRs. @Jorropo lead the actual release so he might have better feedback!
