### ISSUE TITLE
bitswap: reenable unit tests

### ISSUE THREAD

**Issue by BigLep** [ipfs/go-libipfs#327]
## Done Criteria
Bitswap has tests reenabled such that we remove judgement from developers.  CI must be green before we merge.

## Why Important
In the absence of clear signal, developers have sometimes skipping CI checks, which in at least one instance caused a bug to go through. 

## Notes
This isn't intended to be a "fix the flaky tests" effort.  For now we can just rerun the flaky tests X times.  We need to get to a place though where all tests have to pass before we merge.

Internal conversation on this: https://filecoinproject.slack.com/archives/C04SWLJ2QQ4/p1684434613517719

**Comment by Jorropo** [comment]
What we want to do is going through trying to remove the `tests.Flaky` call from the `bitswap/...` tests and see what tests reliably pass and which one do not.

Some flaky tests will be very hard to fix, it is fine to leave `tests.Flaky` for them in some individual PRs, even if the target is to remove all usage of `tests.Flaky` to fix this issue a PR that leave some but increase code coverage is still awesome.

We can view coverage progress here: https://app.codecov.io/gh/ipfs/boxo/tree/main/bitswap

**Comment by BigLep** [comment]
Per sync with PL EngRes Bedrock on 2023-06-30, we'll update with where this sits in the queue (and expected completion date) by 2023-07-07.

**Comment by BigLep** [comment]
I signed off on 2023-07-07 without updating this - my bad.
We expect to complete this this week.
Before doing this work, @Jorropo is tackling the in-progress fixes for https://github.com/ipfs/kubo/issues/9927 and https://github.com/ipfs/boxo/issues/209#issuecomment-1599389206

**Comment by BigLep** [comment]
2023-10-05 conversation: 
- @Jorropo to summarize in this issue what tests are disabled and explain why those tests are disabled.  We believe (but need to confirm) that this is all for a particular bug we aren't going to fix currently.
