### ISSUE TITLE
Go Merkledag Dependency Issues

### ISSUE THREAD

**Issue by avislash** [ipfs/go-libipfs#346]
After upgrading to boxo v0.10.0 I receive the following errors from the indirect merkledag depenedency when attempting to run my program

```
../../go/pkg/mod/github.com/ipfs/go-merkledag@v0.9.0/merkledag.go:26:9: undefined: format.Register
../../go/pkg/mod/github.com/ipfs/go-merkledag@v0.9.0/merkledag.go:27:9: undefined: format.Register
../../go/pkg/mod/github.com/ipfs/go-merkledag@v0.9.0/merkledag.go:28:9: undefined: format.Register
../../go/pkg/mod/github.com/ipfs/go-merkledag@v0.9.0/merkledag.go:30:9: undefined: legacy.RegisterCodec
../../go/pkg/mod/github.com/ipfs/go-merkledag@v0.9.0/merkledag.go:31:9: undefined: legacy.RegisterCodec
../../go/pkg/mod/github.com/ipfs/go-merkledag@v0.9.0/merkledag.go:86:16: undefined: legacy.DecodeNode
../../go/pkg/mod/github.com/ipfs/go-merkledag@v0.9.0/merkledag.go:146:16: undefined: legacy.DecodeNode
../../go/pkg/mod/github.com/ipfs/go-merkledag@v0.9.0/merkledag.go:254:23: undefined: legacy.DecodeNode
```

**Comment by aschmahmann** [comment]
If you update your go-merkledag dependency to [v0.11.0](https://github.com/ipfs/go-merkledag/releases/tag/v0.11.0) you should be fine.

Out of curiosity which dependency brought in go-merkledag for you? Mostly I've seen this import come through ipld/go-car which IIUC the maintainers should be updating this week as well.

**Comment by avislash** [comment]
go-merkledag seems to be getting imported by go-ipfs-http-client which I also have a direct dependency on.

After trying to update go-ipfs-http-client to v0.6.0 I get this issue
```
# github.com/ipfs/go-ipfs-http-client
../../go/pkg/mod/github.com/ipfs/go-ipfs-http-client@v0.6.0/api.go:214:9: cannot use (*RoutingAPI)(api) (value of type *RoutingAPI) as iface.RoutingAPI value in return statement: *RoutingAPI does not implement iface.RoutingAPI (wrong type for method Put)
                have Put(context.Context, string, []byte) error
                want Put(context.Context, string, []byte, ...options.RoutingPutOption) error
../../go/pkg/mod/github.com/ipfs/go-ipfs-http-client@v0.6.0/dag.go:37:16: undefined: format.DefaultBlockDecoder
../../go/pkg/mod/github.com/ipfs/go-ipfs-http-client@v0.6.0/pin.go:204:16: cannot use &pinVerifyRes{…} (value of type *pinVerifyRes) as iface.PinStatus value in send: *pinVerifyRes does not implement iface.PinStatus (missing method Err)

```

So I may have been mistaken that the error was coming from having updated boxo and will ask about this issue in the go-ipfs-http-client repo.

Thanks!

**Comment by Jorropo** [comment]
@avislash this is unrelated, you need to use for `github.com/ipfs/go-ipfs-http-client@master` for the latest `boxo` (we need to release Kubo `-rc1` before to tagging `go-ipfs-http-client`, will do that soon and it should work *automatically*).
