### ISSUE TITLE
Entire Bitswap Test Suite is marked Flaky

### ISSUE THREAD

**Issue by hannahhoward** [ipfs/go-libipfs#399]
When go-bitswap was moved over, the entire test suite was marked Flaky (as in every single individual test). It has remained this way for 3 months. While there were plenty of failures in the tests, the vast majority of individual tests are not flaky, and not having this test suite seems like a quick path to lots of regressions. Those tests that are not flaky should be re-enabled, hopefully as soon as possible.

**Comment by Jorropo** [comment]
Duplicate :wink: https://github.com/ipfs/boxo/issues/327
