### ISSUE TITLE
How to use Boxo library or SDK for IPFS with Go language?

### ISSUE THREAD

**Issue by unicornlox** [ipfs/go-libipfs#451]
Hello,

I could not find any documentation on how to use ipfs boxo. In short, I want to use ipfs with the go language, and when I look at the information about kubo, there are old libraries. Where are the current documents on how to use ipfs with go? If anyone has information, please help.

Thank you for your support.

**Comment by lidel** [comment]
@unicornlox  does https://github.com/ipfs/kubo/issues/10096#issuecomment-1723520641 answered your question, or do you feel we should add more examples in Boxo?

**Comment by BigLep** [comment]
2023-10-05 maintainer conversation: this should be closed because lacking author input.  @hacdias is going to get the bot going for this repo.

**Comment by hacdias** [comment]
@BigLep I checked some other PRs and they've been hit by the bot, I'm not sure why this one hasn't. cc @ipfs/ipdx

**Comment by galargh** [comment]
@hacdias That's because it still had [need/triage](https://github.com/ipfs/boxo/labels/need%2Ftriage) badge on. That label prevents the automation from automatically closing an issue.
