### ISSUE TITLE
http: superfluous response.WriteHeader

### ISSUE THREAD

**Issue by cachalots** [ipfs/go-libipfs#487]
There are many error logs in the IPFS gateway.
```
http: superfluous response.WriteHeader call from github.com/ipfs/boxo/gateway.webError (errors.go:175)

http: superfluous response.WriteHeader call from github.com/ipfs/boxo/gateway.webError (errors.go:165)
```
Calling writeError after writeHeader will trigger this error. I'm not sure if this part of the code is causing it, but this code will trigger this issue.
https://github.com/ipfs/boxo/blob/6602207a8fa3624bfd52d8859c544abdb1ef0324/gateway/handler.go#L921-L928

**Comment by lidel** [comment]
@cachalots 
- how are you using `boxo/gateway`? as a library in you app?
- do you have more than a single mux / listener / instance of gateway?

Mind providing the smallest `demo.go` that reproduces the issue?

**Comment by cachalots** [comment]
@lidel https://github.com/4everland/ipfs-servers/blob/dev/app/gateway/internal/server/http.go 
Same usage as in example, only replacing the implementation of blockstore. 
In theory, if there are enough requests, the gateway example should also reproduce this error. This error was reported by net/http, so it's not easy to assert which location triggered this error.
