### ISSUE TITLE
compute cid programaticaly like `--only-hash`

### ISSUE THREAD

**Issue by Vikram710** [ipfs/go-libipfs#512]
I am trying to generate ipfs cid programmatically in golang ( replicate the functionality of ipfs add --only-hash ). 

```
func GetIpfsCid() {
	data, _ := os.ReadFile("./abc.txt")
	chunks := chunker.NewSizeSplitter(bytes.NewReader(data), 1024*256)
	root := merkledag.NodeWithData(nil)
	for {
		chunk, err := chunks.NextBytes()
		if err == io.EOF {
			break
		} else if err != nil {
			panic(err)
		}

		unixFSWrappedSampleData := unixfs.FilePBData(chunk, uint64(len(chunk)))
                fmt.Println(node.Cid().String())
		node := merkledag.NodeWithData(unixFSWrappedSampleData)
		root.AddNodeLink(node.Cid().String(), node)
	}
	fmt.Println(root.Cid().String())
}
```

my file size is around 2.2 mb, chunked into 256kb 
`fmt.Println(node.Cid().String()) matches with the 9 chunks created in https://dag.ipfs.tech/ ` 

I found an npm package ipfs-only-hash which does what I want. 
Hoping if someone could help point me towards the same implementation in golang

**Comment by Jorropo** [comment]
The short answer is that no one worked on a deterministic Chunking spec yet, there is no way to be sure `--only-hash` gives you back the same answer across various implementations.

I'll post an example on how to do that anyway later but I can't promise it will give you the same cids with other applications or in the future.

I can open a meta spec issue about deterministic Chunking if you are interested to work on that.

**Comment by Vikram710** [comment]
Thanks. Could you please provide an example? It would be beneficial, and I plan to work on this anyway will contribute to the issue created once done.

**Comment by sharathguvvala** [comment]
Hi @Jorropo I was also exploring a similar challenge to generate the ipfs cid in go. You mentioned you'd post an example on deterministic chunking. Could you please share that, if by any chance you have it ready?
Thank you in advance!

**Comment by Jorropo** [comment]
I'll find time next week, I think you missunderstood, there are no specs this can break at any time.

**Comment by Jorropo** [comment]
Triage notes:
- I'll do an example which accept parameters and has no defaults to make it clear this is not specified.

**Comment by aschmahmann** [comment]
You should be able to ingest a file as UnixFS using:

https://github.com/ipfs/boxo/blob/79cb4e2886d72af06f3b102982520a743835c02f/examples/unixfs-file-cid/main.go#L149-L177

you can choose whichever parameters you want for UnixFS encoding there.

**Comment by lidel** [comment]
@Vikram710  in the future you may want to ask support questions like this in https://discuss.ipfs.tech/c/help/13 where wider community has more eyes. We try to limit github to bugs and feature requests. :pray:
