### ISSUE TITLE
Boxo @latest v0.16.0 doesn't have modules which boxo v0.15.0 has

### ISSUE THREAD

**Issue by ofman** [ipfs/go-libipfs#522]
Looks like new version of boxo doesn't have required coreiface modules.

I have tried an official ipfs kubo example from [here](https://github.com/ipfs/kubo/tree/master/docs/examples/kubo-as-a-library) and after import 'icore "github.com/ipfs/boxo/coreiface"' into main.go looks like latest version of boxo v0.16.0 doesn't have modules v0.15.0 had.

Terminal paste below after "go mod tidy" command:
`github.com/ipfs/boxo/coreiface: module github.com/ipfs/boxo@latest found (v0.16.0), but does not contain package github.com/ipfs/boxo/coreiface
github.com/ipfs/boxo/coreiface/options: module github.com/ipfs/boxo@latest found (v0.16.0), but does not contain package github.com/ipfs/boxo/coreiface/options`

**Comment by Jorropo** [comment]
Thx for your report,
We removed it in `v0.16.0` https://github.com/ipfs/boxo/blob/main/CHANGELOG.md#removed-1

See:
- https://github.com/ipfs/kubo/pull/10237
- https://github.com/ipfs/boxo/pull/517

With Boxo `v0.16.0` you need Kubo `v0.25.0-rc1` and later you can use `github.com/ipfs/kubo/core/coreiface`

If you want to use Kubo, please use the version of boxo used by Kubo.
You can do `go get github.com/ipfs/kubo@latest && go mod tidy` and it should pull up the version of boxo used by Kubo.

**Comment by ofman** [comment]
Seems like `go get github.com/ipfs/kubo@latest && go mod tidy ` still gets non rc1 version on debian 12 `go version go1.21.4 linux/amd64` but exact below command worked really well (added `@v0.25.0-rc1` instead of `@latest`):
`go get github.com/ipfs/kubo@v0.25.0-rc1 && go mod tidy`

Thanks! :)

**Comment by Jorropo** [comment]
`@latest` would have got Kubo `v0.24.0` and it would also download boxo `v0.15.0` if you had a clean `go.mod` (not added boxo `v0.16.0` already)
