### ISSUE TITLE
example: add directory to UnixFS example

### ISSUE THREAD

**Issue by mostcute** [ipfs/go-libipfs#674]
now the repo have an example how to add a file to bitswap server and download from a client

we also need a example to show how to add a directory struct to bitswap server (like ipfs add dir or ipfs add file -w )and how client read the directory struct and download whole dir or download single file in the dir

**Comment by lidel** [comment]
Good suggestion, this feels like a duplicate of https://github.com/ipfs/boxo/issues/663, let's continue there.
