### ISSUE TITLE
[ipfs/go-bitswap] Check wantlists by multihash

### ISSUE THREAD

**Issue by Winterhuman** [ipfs/go-libipfs#71]
As mentioned at https://github.com/ipfs/boxo/issues/420, Bitswap apparently still checks wantlists by CID instead of multihash

**Comment by guseggert** [comment]
Sounds reasonable. When we pick this up, make sure specs are up-to-date https://github.com/ipfs/specs/blob/main/BITSWAP.md#bitswap-110

**Comment by lidel** [comment]
Continued in https://github.com/ipfs/boxo/issues/420
