### ISSUE TITLE
[ipfs/go-bitswap] update go-lipb2p

### ISSUE THREAD

**Issue by marten-seemann** [ipfs/go-libipfs#72]
This repo should be updated to use go-libp2p v0.22.0 (which deprecates go-libp2p-core).

The main change that needs to happen (other than a rewrite of import paths) is a change of this test: https://github.com/ipfs/go-bitswap/blob/4e3736a773545bf09d5178a2be24043b76560f87/network/ipfs_impl_test.go#L501-L516

The stream notifications were removed from the `Notifiee` interface a while ago: https://github.com/libp2p/go-libp2p-core/pull/250

**Comment by Jorropo** [comment]
it has been done since
