### ISSUE TITLE
Cut a new release with quic-go 0.48.2

### ISSUE THREAD

**Issue by jimmykarily** [ipfs/go-libipfs#744]
Security scanners have started complaining about quic-go (https://osv.dev/vulnerability/GO-2024-3302) and it needs to be bumped to `v0.48.2`. This is already bumped in this repository but there is no tag/release for this yet.

I want to open PRs on dependant projects to fix this but it's better if there is a release to bump to (bumping to arbitrary commits from master might not get those PRs accepted)

e.g. [this project](https://github.com/libp2p/go-libp2p-kad-dht/blob/88ef336f9f89b749d9ee37f3dcb3a4830faec33f/go.mod#L15) needs the bump

Background: our Kairos pipelines are failing security scans: https://github.com/kairos-io/kairos/actions/runs/12194383948/job/34018136463?pr=3055

**Comment by jimmykarily** [comment]
Since it's being used as a library, this bump is not necessarily required ([already discussed this on another project](https://github.com/libp2p/go-libp2p-pubsub/pull/586#issuecomment-2527124684)) so feel free to keep it or close it.

**Comment by gammazero** [comment]
Fixed by #748
